hoooooojjjj/New_GraduART

.vscode/settings.json
src/components/Router.jsx
src/pages/PaymentApproval/PaymentApproval.jsx
src/pages/PaymentApproval/PaymentApprovalStyles.js

-[ㅇ] 기능 추가
-[] 기능 삭제
-[] 버그 수정
PaymentApproval -> main
Payment Approval 페이지 반응형 퍼블리싱 완료 (퍼블리싱 단계에서는 버튼 클릭 시 PaymentSuccess 페이지로 리디렉션되도록 구현해둠)
https://github.com/user-attachments/assets/93c9ebd0-110d-42d0-8362-5550ee1af0f6
https://github.com/user-attachments/assets/ec07510a-4ae4-4be9-be1f-98fe4cde7253

Feat: PaymentApproval 데스크탑/모바일 퍼블리싱

---

package-lock.json
package.json
src/components/DepartmentHeader/DepartmentHeader.jsx
src/components/common/ErrorMessage.jsx
src/components/common/Loading.jsx
src/components/footer/Footer.jsx
src/pages/Artwork/Artwork.jsx
src/pages/Artwork/ArtworkStyle.js
src/pages/DeptDetail/DeptDetail.jsx
src/pages/DeptDetail/components/exhibition/DeptDetailExhibitionComponent.jsx
src/utils/axios.js

-[0] 기능 추가
-[] 기능 삭제
-[] 버그 수정
minseok_artworkPage-> main
작품 상세페이지 api연결, 과별페이지 작품 api연결

Minseok artwork page

---

package-lock.json
package.json
src/components/DepartmentHeader/DepartmentHeader.jsx
src/components/common/ErrorMessage.jsx
src/components/common/Loading.jsx
src/components/footer/Footer.jsx
src/pages/Artwork/Artwork.jsx
src/pages/Artwork/ArtworkStyle.js
src/pages/Department/Department.json
src/pages/DeptDetail/DeptDetail.jsx
src/pages/DeptDetail/components/dept_header/DeptDetailHeader.jsx
src/pages/DeptDetail/components/exhibition/DeptDetailExhibitionComponent.jsx
src/pages/Landing/DeptSection.jsx
src/pages/Landing/TitleSection.jsx
src/utils/axios.js

-[0] 기능 추가
-[0] 기능 삭제
-[] 버그 수정
Eunjae_DepartmentPage -> main
- 과별 페이지 기능 구현(상단 동그라미 클릭시 해당 과 페이지로 이동, 과별 페이지 내 검색 기능) 
- 메인 페이지 학과(금속공예, 도예로) 변경, 그 외의 공간은 호버, 클릭 안 되도록 기능 축소
아직 금속공예전공, 도예전공이 백에 안 만들어져서 작품 불러오기 및 검색 기능이 잘 작동하고 있는지 확인하지 못했음. 17일까지 확인하고 코드 수정할 예정.

Eunjae department page

---

src/components/DepartmentHeader/DepartmentHeader.jsx
src/components/search/ItemSearch.jsx
src/components/search/SearchOverlay.jsx
src/pages/Artwork/Artwork.jsx
src/pages/Cart/Cart.jsx
src/pages/Cart/CartStyle.js
src/pages/DeptDetail/components/dept_header/DeptDetailHeaderStyles.js
src/pages/Landing/DeptSection.jsx
src/pages/Payment/Payment.jsx
src/pages/Serach 2.jsx

-[0] 기능 추가
-[] 기능 삭제
-[] 버그 수정
minseok_CartPage -> main
장바구니 기능, 검색기능 추가

민석 장바구니, 검색기능

---

src/components/search/SearchOverlay.jsx
src/components/search/SerachOverlayStyle.js
src/pages/Artwork/ArtworkStyle.js
src/pages/Cart/Cart.jsx
src/pages/Cart/CartStyle.js
src/pages/DeptDetail/components/exhibition/DeptDetailExhibitionComponent.jsx

-[] 기능 추가
-[] 기능 삭제
-[0] 버그 수정
minseok_Cart -> main
장바구니 ui 개선

FIX: 장바구니 구조

---

src/components/Router.jsx
src/pages/Cart/Cart.jsx
src/pages/Payment/Payment.jsx
src/pages/PaymentApproval/PaymentApproval.jsx
src/pages/PaymentInfo/PaymentInfo.jsx
src/pages/PaymentSuccess/PaymentSuccess.jsx

-[✅] 기능 추가
main <- AfterPaymentHandle
결제 처리, 결제 후 핸들링 관련 기능들 일부 추가했습니다.
로컬에서 이상없습니다

Payment Handling Functions

---

src/components/Router.jsx
src/pages/Cart/Cart.jsx
src/pages/Payment/Payment.jsx
src/pages/PaymentApproval/PaymentApproval.jsx
src/pages/PaymentInfo/PaymentInfo.jsx
src/pages/PaymentSuccess/PaymentSuccess.jsx

결제 연결완료
-[✅] 기능 추가
main ← PaymentFix
결제 연결완료
(로컬에서) 정상 작동

[Feat] Payment

---

src/components/footer/Footer.jsx
src/pages/Artwork/Artwork.jsx
src/pages/Payment/Payment.jsx
src/pages/Payment/PaymentStyle.js

결제하기 버튼 작동하도록 변수명 변환, 푸터 수정
-[✅] 버그 수정
main <- PaymentInfoFix
푸터 수정 및 결제하기 로직 수정
로컬에서 이상 없음

[Fix] Footer Change, Purchase Button Modified

---

src/pages/My/MyStyle.js
src/pages/PaymentInfo/PaymentInfo.jsx
src/pages/PaymentInfo/PaymentInfoStyle.js

-[ㅇ] 기능 추가
-[] 기능 삭제
-[] 버그 수정
ex) feat/payinfo -> main
ex) Payment Info page 기능 구현 및 퍼블리싱

[FEAT] Payment Info page overall function

---

src/pages/Artwork/Artwork.jsx

-[0] 기능 추가
-[] 기능 삭제
-[] 버그 수정
DeliveryDate -> main
배송기간 추가했습니다.

FEAT: 배송기간 추가

---

src/pages/Payment/Payment.jsx
src/pages/Payment/PaymentStyle.js

-[] 기능 추가
-[] 기능 삭제
-[ㅇ] 버그 수정
ex) fix/payment -> main
기본 주소 입력란 인풋이 안 들어가는 문제 해결

[FIX] payment address form issue

---

src/pages/Artwork/Artwork.jsx

[FIX] 친절한 alert

---

src/components/footer/Footer.jsx

fix: minseo phonenumber

---

src/GlobalColors.css
src/components/DepartmentHeader/DepartmentHeaderStyle.js
src/components/footer/FooterStyles.js
src/pages/Artwork/Artwork.jsx
src/pages/Artwork/ArtworkStyle.js

-[ㅇ] 기능 추가
-[] 기능 삭제
-[] 버그 수정
ex) feat/fixfooter -> main
헤더, 푸터, 상품 상세 페이지의 색상 변경

[FIX] header, footer, deptdetail color

---

public/index.html
src/pages/Payment/AdressModal.js
src/pages/Payment/Payment.jsx
src/pages/Payment/PaymentStyle.js

-[ㅇ] 기능 추가
-[] 기능 삭제
-[] 버그 수정
ex) feat/kakaoaddress -> main
address에서 기본 주소 카카오 모달로 입력받도록 기능 구현

[FEAT] kakao address search

---

src/components/Router.jsx
src/pages/My/My.jsx
src/pages/PaymentInfo/PaymentInfo.jsx
src/pages/Refund/Refund.jsx

[FIX] routing problem

---

src/components/Router.jsx
src/pages/My/My.jsx
src/pages/PaymentInfo/PaymentInfo.jsx

-[] 기능 추가
-[] 기능 삭제
-[ㅇ] 버그 수정
fix/minor -> main
payment info 리디렉션 시 500 에러가 뜨는 것을 해결

[FIX] payment info page connection

---

src/pages/PaymentInfo/PaymentInfo.jsx

-[] 기능 추가
-[] 기능 삭제
-[ㅇ] 버그 수정
fix/minor => main
앞선 커밋에 이은 커밋

[FIX] paymentinfo page error

---

src/pages/PaymentInfo/PaymentInfo.jsx
src/utils/axios.js

[FIX] payment info axios error

---

src/pages/Artwork/ArtworkStyle.js
src/pages/Cart/CartStyle.js
src/pages/Landing/DeptSection.jsx
src/pages/Payment/Payment.jsx
src/pages/SignIn/SignIn.jsx

-[] 기능 추가
-[] 기능 삭제
-[ㅇ] 버그 수정
fix/minor => main
1) artwork 페이지 색 에러 수정
2) 사진 안뜨는 문제 해결

[FIX] artwork bg, cart img visibilty

---

src/pages/Payment/PaymentStyle.js
src/pages/PaymentInfo/PaymentInfoStyle.js
src/pages/Refund/RefundStyle.js

-[] 기능 추가
-[] 기능 삭제
-[ㅇ] 버그 수정
fix/minor -> main
장바구니, 결제 관련 페이지 등에 상품 이미지 불러옴

[Fix] image css

---

src/pages/My/My.jsx
src/pages/My/MyStyle.js
src/pages/Payment/Payment.jsx

[FIX] image loading issue

---

src/pages/DeptDetail/DeptDetailStyles.js
src/pages/Refund/RefundStyle.js

-[] 기능 추가
-[] 기능 삭제
-[ㅇ] 버그 수정
ex) fix/qa -> main
1) 환불 페이지 css 교체
2) 학과 페이지 푸터 css 교체

[FIX] refund css style, deptdetail footer style

---

src/pages/Refund/RefundStyle.js

[FIX] refund css style

---

src/pages/My/My.jsx
src/pages/Payment/Payment.jsx
src/pages/PaymentInfo/PaymentInfo.jsx
src/pages/PaymentInfo/PaymentInfoStyle.js
src/pages/Refund/RefundStyle.js

결제내역 조회 수정
-[] 기능 추가
-[] 기능 삭제
-[] 버그 수정

[Fix] 결제정보, 버튼 QA

---

src/pages/My/My.jsx
src/pages/PaymentInfo/PaymentInfo.jsx
src/pages/Refund/Refund.jsx
src/pages/Refund/RefundStyle.js

결제 승인 시각 표현, 환불신청여부 State 관리
-[✅] 버그 수정
main ← Daeyu_QA
결제 승인 시각 표현, 환불신청여부 State 관리, 기타 소소한 변경사항
취소/환불 신청하기 로직이 로컬 백엔드에서 돌지 않는 걸 제외하면 이상없습니다

[Fix] 결제 승인 시각, 취소/환불 로직

---

src/components/DepartmentHeader/DepartmentHeaderStyle.js
src/components/search/ItemSearchStyle.js
src/pages/Cart/CartStyle.js
src/pages/DeptDetail/components/exhibition/DeptDetailExhibitionComponentStyles.js
src/pages/My/My.jsx
src/pages/My/MyStyle.js
src/pages/Refund/RefundStyle.js

-[] 기능 추가
-[] 기능 삭제
-[0] 버그 수정
minseokqa-> main
민석 qa 및 가독성 수정

민석 qa 및 가독성 수정

---

src/pages/Department/Department.json
src/pages/DeptDetail/DeptDetailStyles.js
src/pages/DeptDetail/components/dept_header/DeptDetailHeader.jsx
src/pages/DeptDetail/components/dept_header/DeptDetailHeaderStyles.js
src/pages/DeptDetail/components/dept_info/DeptDetailDeptInfoComponentStyles.js
src/pages/DeptDetail/components/exhibition/DeptDetailExhibitionComponent.jsx

2. **~~Metal → Metalwork로 변경~~**
3. **~~전시명 표기가 가능할 지, 전시 설명을 추가할 수 있는 지 (2024 판매전 'ON&ON' 등) (사이트 제목과 혼동되어 졸업전시로 인지될 가능성)~~**

chore: Update styles for responsive design in DeptDetail page

---

src/pages/Artwork/Artwork.jsx
src/pages/Artwork/ArtworkStyle.js

이미지 상세정보 섹션 수정
-[✅] 버그 수정
main ← Daeyu_QA
폰트 크기 및 창작자 SNS 표시 수정했습니다

[Fix] 폰트 및 이미지 상세 표현

---

src/pages/Landing/TitleSection.jsx
src/pages/SignIn/ GoogleCallback.jsx

fix:mainpage hover animation
